import { Prisma } from '@prisma/client';
export {
  UserObject,
  UserIdFieldObject,
  UserFirstNameFieldObject,
  UserLastNameFieldObject,
  UserBirthdateFieldObject,
  UserLoginFieldObject,
  UserPasswordFieldObject,
  UserPostsFieldObject,
  UserCommentsFieldObject,
  UserCreatedAtFieldObject,
  UserUpdatedAtFieldObject,
  UserProfileFieldObject,
  UserFollowersFieldObject,
  UserFollowingFieldObject
} from './User';
export {
  PostObject,
  PostIdFieldObject,
  PostTitleFieldObject,
  PostContentFieldObject,
  PostAuthorFieldObject,
  PostCommentsFieldObject,
  PostAuthorIdFieldObject,
  createManyPostMutation,
  createOnePostMutation,
  deleteManyPostMutation,
  deleteOnePostMutation,
  updateManyPostMutation,
  updateOnePostMutation,
  upsertOnePostMutation,
  createManyPostMutationObject,
  createOnePostMutationObject,
  deleteManyPostMutationObject,
  deleteOnePostMutationObject,
  updateManyPostMutationObject,
  updateOnePostMutationObject,
  upsertOnePostMutationObject,
  findFirstPostQuery,
  findManyPostQuery,
  countPostQuery,
  findUniquePostQuery,
  findFirstPostQueryObject,
  findManyPostQueryObject,
  countPostQueryObject,
  findUniquePostQueryObject
} from './Post';
export {
  ExtraModalObject,
  ExtraModalIdFieldObject,
  ExtraModalTitleFieldObject,
  ExtraModalCreatedAtFieldObject,
  ExtraModalUpdatedAtFieldObject,
  createManyExtraModalMutation,
  createOneExtraModalMutation,
  deleteManyExtraModalMutation,
  deleteOneExtraModalMutation,
  updateManyExtraModalMutation,
  updateOneExtraModalMutation,
  upsertOneExtraModalMutation,
  createManyExtraModalMutationObject,
  createOneExtraModalMutationObject,
  deleteManyExtraModalMutationObject,
  deleteOneExtraModalMutationObject,
  updateManyExtraModalMutationObject,
  updateOneExtraModalMutationObject,
  upsertOneExtraModalMutationObject,
  findFirstExtraModalQuery,
  findManyExtraModalQuery,
  countExtraModalQuery,
  findUniqueExtraModalQuery,
  findFirstExtraModalQueryObject,
  findManyExtraModalQueryObject,
  countExtraModalQueryObject,
  findUniqueExtraModalQueryObject
} from './ExtraModal';
export {
  CommentObject,
  CommentIdFieldObject,
  CommentCommentFieldObject,
  CommentAuthorFieldObject,
  CommentPostFieldObject,
  CommentAuthorIdFieldObject,
  CommentPostIdFieldObject,
  createManyCommentMutation,
  createOneCommentMutation,
  deleteManyCommentMutation,
  deleteOneCommentMutation,
  updateManyCommentMutation,
  updateOneCommentMutation,
  upsertOneCommentMutation,
  createManyCommentMutationObject,
  createOneCommentMutationObject,
  deleteManyCommentMutationObject,
  deleteOneCommentMutationObject,
  updateManyCommentMutationObject,
  updateOneCommentMutationObject,
  upsertOneCommentMutationObject,
  findFirstCommentQuery,
  findManyCommentQuery,
  countCommentQuery,
  findUniqueCommentQuery,
  findFirstCommentQueryObject,
  findManyCommentQueryObject,
  countCommentQueryObject,
  findUniqueCommentQueryObject
} from './Comment';
export {
  ProfileObject,
  ProfileIdFieldObject,
  ProfileBioFieldObject,
  ProfileUserFieldObject,
  ProfileUserIdFieldObject,
  createManyProfileMutation,
  createOneProfileMutation,
  deleteManyProfileMutation,
  deleteOneProfileMutation,
  updateManyProfileMutation,
  updateOneProfileMutation,
  upsertOneProfileMutation,
  createManyProfileMutationObject,
  createOneProfileMutationObject,
  deleteManyProfileMutationObject,
  deleteOneProfileMutationObject,
  updateManyProfileMutationObject,
  updateOneProfileMutationObject,
  upsertOneProfileMutationObject,
  findFirstProfileQuery,
  findManyProfileQuery,
  countProfileQuery,
  findUniqueProfileQuery,
  findFirstProfileQueryObject,
  findManyProfileQueryObject,
  countProfileQueryObject,
  findUniqueProfileQueryObject
} from './Profile';
export {
  FollowObject,
  FollowFromIdFieldObject,
  FollowToIdFieldObject,
  FollowFromFieldObject,
  FollowToFieldObject,
  createManyFollowMutation,
  createOneFollowMutation,
  deleteManyFollowMutation,
  deleteOneFollowMutation,
  updateManyFollowMutation,
  updateOneFollowMutation,
  upsertOneFollowMutation,
  createManyFollowMutationObject,
  createOneFollowMutationObject,
  deleteManyFollowMutationObject,
  deleteOneFollowMutationObject,
  updateManyFollowMutationObject,
  updateOneFollowMutationObject,
  upsertOneFollowMutationObject,
  findFirstFollowQuery,
  findManyFollowQuery,
  countFollowQuery,
  findUniqueFollowQuery,
  findFirstFollowQueryObject,
  findManyFollowQueryObject,
  countFollowQueryObject,
  findUniqueFollowQueryObject
} from './Follow';
export {
  UnrelatedObject,
  UnrelatedIdFieldObject,
  UnrelatedNameFieldObject,
  createManyUnrelatedMutation,
  createOneUnrelatedMutation,
  deleteManyUnrelatedMutation,
  deleteOneUnrelatedMutation,
  updateManyUnrelatedMutation,
  updateOneUnrelatedMutation,
  upsertOneUnrelatedMutation,
  createManyUnrelatedMutationObject,
  createOneUnrelatedMutationObject,
  deleteManyUnrelatedMutationObject,
  deleteOneUnrelatedMutationObject,
  updateManyUnrelatedMutationObject,
  updateOneUnrelatedMutationObject,
  upsertOneUnrelatedMutationObject,
  findFirstUnrelatedQuery,
  findManyUnrelatedQuery,
  countUnrelatedQuery,
  findUniqueUnrelatedQuery,
  findFirstUnrelatedQueryObject,
  findManyUnrelatedQueryObject,
  countUnrelatedQueryObject,
  findUniqueUnrelatedQueryObject
} from './Unrelated';
export {
  IdOnlyObject,
  IdOnlyIdFieldObject,
  createManyIdOnlyMutation,
  createOneIdOnlyMutation,
  deleteManyIdOnlyMutation,
  deleteOneIdOnlyMutation,
  updateManyIdOnlyMutation,
  updateOneIdOnlyMutation,
  upsertOneIdOnlyMutation,
  createManyIdOnlyMutationObject,
  createOneIdOnlyMutationObject,
  deleteManyIdOnlyMutationObject,
  deleteOneIdOnlyMutationObject,
  updateManyIdOnlyMutationObject,
  updateOneIdOnlyMutationObject,
  upsertOneIdOnlyMutationObject,
  findFirstIdOnlyQuery,
  findManyIdOnlyQuery,
  countIdOnlyQuery,
  findUniqueIdOnlyQuery,
  findFirstIdOnlyQueryObject,
  findManyIdOnlyQueryObject,
  countIdOnlyQueryObject,
  findUniqueIdOnlyQueryObject
} from './IdOnly';
export {
  WithoutIDObject,
  WithoutIDNameFieldObject,
  createManyWithoutIDMutation,
  createOneWithoutIDMutation,
  deleteManyWithoutIDMutation,
  deleteOneWithoutIDMutation,
  updateManyWithoutIDMutation,
  updateOneWithoutIDMutation,
  upsertOneWithoutIDMutation,
  createManyWithoutIDMutationObject,
  createOneWithoutIDMutationObject,
  deleteManyWithoutIDMutationObject,
  deleteOneWithoutIDMutationObject,
  updateManyWithoutIDMutationObject,
  updateOneWithoutIDMutationObject,
  upsertOneWithoutIDMutationObject,
  findFirstWithoutIDQuery,
  findManyWithoutIDQuery,
  countWithoutIDQuery,
  findUniqueWithoutIDQuery,
  findFirstWithoutIDQueryObject,
  findManyWithoutIDQueryObject,
  countWithoutIDQueryObject,
  findUniqueWithoutIDQueryObject
} from './WithoutID';
export {
  WithScalarsObject,
  WithScalarsIdFieldObject,
  WithScalarsStringFieldObject,
  WithScalarsBooleanFieldObject,
  WithScalarsIntFieldObject,
  WithScalarsFloatFieldObject,
  WithScalarsDecimalFieldObject,
  WithScalarsBigintFieldObject,
  WithScalarsDatetimeFieldObject,
  WithScalarsBytesFieldObject,
  createManyWithScalarsMutation,
  createOneWithScalarsMutation,
  deleteManyWithScalarsMutation,
  deleteOneWithScalarsMutation,
  updateManyWithScalarsMutation,
  updateOneWithScalarsMutation,
  upsertOneWithScalarsMutation,
  createManyWithScalarsMutationObject,
  createOneWithScalarsMutationObject,
  deleteManyWithScalarsMutationObject,
  deleteOneWithScalarsMutationObject,
  updateManyWithScalarsMutationObject,
  updateOneWithScalarsMutationObject,
  upsertOneWithScalarsMutationObject,
  findFirstWithScalarsQuery,
  findManyWithScalarsQuery,
  countWithScalarsQuery,
  findUniqueWithScalarsQuery,
  findFirstWithScalarsQueryObject,
  findManyWithScalarsQueryObject,
  countWithScalarsQueryObject,
  findUniqueWithScalarsQueryObject
} from './WithScalars';
import { builder } from '../builder';

export const BatchPayload = builder.objectType(builder.objectRef<Prisma.BatchPayload>('BatchPayload'), {
  description: 'Batch payloads from prisma.',
  fields: (t) => ({
    count: t.exposeInt('count', { description: 'Prisma Batch Payload', nullable: false }),
  }),
});

export const modelNames = [
  'User',
  'Post',
  'ExtraModal',
  'Comment',
  'Profile',
  'Follow',
  'Unrelated',
  'IdOnly',
  'WithoutID',
  'WithScalars',
] as const;

export type Model = typeof modelNames[number];
